import { useState, useEffect } from 'react'
import { adminService } from '../../services/adminService'
import StatsCard from '../../components/admin/StatsCard'
import RevenueChart from '../../components/admin/RevenueChart'
import ActivityLog from '../../components/admin/ActivityLog'
import LoadingSpinner from '../../components/common/LoadingSpinner'
import { Users, Image, DollarSign, CreditCard } from 'lucide-react'

const AdminDashboard = () => {
  const [stats, setStats] = useState(null)
  const [revenueData, setRevenueData] = useState([])
  const [activities, setActivities] = useState([])
  const [loading, setLoading] = useState(true)

  useEffect(() => {
    loadDashboardData()
  }, [])

  const loadDashboardData = async () => {
    try {
      const [statsData, revenueStats] = await Promise.all([
        adminService.getDashboardStats(),
        adminService.getRevenueStats('month')
      ])

      setStats(statsData)
      setRevenueData(revenueStats?.data || [])
      
      // Mock activities
      setActivities([
        { type: 'user_registered', description: 'New user registered: john@example.com', timestamp: new Date() },
        { type: 'image_generated', description: 'Image generated by user123', timestamp: new Date() },
        { type: 'payment_received', description: 'Payment of $29.99 received', timestamp: new Date() },
      ])
    } catch (error) {
      console.error('Failed to load dashboard data:', error)
    } finally {
      setLoading(false)
    }
  }

  if (loading) {
    return (
      <div className="flex items-center justify-center h-full">
        <LoadingSpinner size="xl" />
      </div>
    )
  }

  return (
    <div className="space-y-6">
      <h1 className="text-3xl font-bold text-gray-900 dark:text-white">
        Dashboard Overview
      </h1>

      {/* Stats Grid */}
      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6">
        <StatsCard
          title="Total Users"
          value={stats?.totalUsers || 0}
          change={12.5}
          icon={Users}
          trend="up"
        />
        <StatsCard
          title="Total Images"
          value={stats?.totalImages || 0}
          change={8.3}
          icon={Image}
          trend="up"
        />
        <StatsCard
          title="Revenue"
          value={`$${stats?.revenue || 0}`}
          change={15.7}
          icon={DollarSign}
          trend="up"
        />
        <StatsCard
          title="Active Subscriptions"
          value={stats?.activeSubscriptions || 0}
          change={-2.4}
          icon={CreditCard}
          trend="down"
        />
      </div>

      {/* Charts and Activity */}
      <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
        <RevenueChart data={revenueData} />
        <ActivityLog activities={activities} />
      </div>
    </div>
  )
}

export default AdminDashboard